tables:
- source:
    tableName: videos
    schemaName: music_catalog
    databaseName: vevodb
  target:
    tableName: VIDEOS
    schemaName: MUSIC_CATALOG
  columnNamesToPartitionBy:
  - video_id
- source:
    tableName: daily_streams
    schemaName: analytics
    databaseName: vevodb
  target:
    tableName: DAILY_STREAMS
    schemaName: ANALYTICS
  columnNamesToPartitionBy:
  - stream_id
- source:
    tableName: artists
    schemaName: music_catalog
    databaseName: vevodb
  target:
    tableName: ARTISTS
    schemaName: MUSIC_CATALOG
  columnNamesToPartitionBy:
  - artist_id
- source:
    tableName: ad_campaigns_history
    schemaName: operations
    databaseName: vevodb
  target:
    tableName: AD_CAMPAIGNS_HISTORY
    schemaName: OPERATIONS
- source:
    tableName: user_engagement
    schemaName: analytics
    databaseName: vevodb
  target:
    tableName: USER_ENGAGEMENT
    schemaName: ANALYTICS
  columnNamesToPartitionBy:
  - engagement_id
- source:
    tableName: content_moderation
    schemaName: operations
    databaseName: vevodb
  target:
    tableName: CONTENT_MODERATION
    schemaName: OPERATIONS
  columnNamesToPartitionBy:
  - moderation_id
- source:
    tableName: ad_placements
    schemaName: operations
    databaseName: vevodb
  target:
    tableName: AD_PLACEMENTS
    schemaName: OPERATIONS
  columnNamesToPartitionBy:
  - placement_id
- source:
    tableName: channels
    schemaName: music_catalog
    databaseName: vevodb
  target:
    tableName: CHANNELS
    schemaName: MUSIC_CATALOG
  columnNamesToPartitionBy:
  - channel_id
- source:
    tableName: ad_campaigns
    schemaName: operations
    databaseName: vevodb
  target:
    tableName: AD_CAMPAIGNS
    schemaName: OPERATIONS
  columnNamesToPartitionBy:
  - campaign_id
defaultTableConfiguration:
  target:
    databaseName: VEVODB_UAT
  synchronization:
    strategy: none
  extraction:
    strategy: unload
    externalStage: '@VEVODB_UAT.PUBLIC.MIGRATION_STAGE'
